#!/bin/bash
if [ "$#" = 2 ] && [ "$1" = '-N' ]; then
  name="`basename "$2"`"
  if [ "$name" = "firefox-${PV}esr.source.tar.xz" ]; then
    cp "$DISTDIR/$name" . && exit 0
  fi
fi
exec /usr/bin/wget "$@"
